location:
  place_name: "Çorlu, Tekirdağ, Türkiye"

problem:
  strategy: "from_scenario"
  scenario_filepath: "data/scenarios/corlu_varsayilan_10_durak.json"
  
  random_stops:
    num_stops: 15
    min_demand: 1
    max_demand: 10
  
  dbscan:
    eps: 0.01 
    min_samples: 5

aco:
  # Araç filosu ve kapasiteleri. Karınca sayısı bu listenin uzunluğu kadar olacaktır.
  vehicle_fleet: [50, 50]

  # Bir aracın depodan her çıkışının kilometre cinsinden ek maliyeti.
  vehicle_fixed_cost: 0.0

  strategy: "mmas"

  # Algoritma parametreleri
  iterations: 50
  alpha: 1.0
  beta: 2.0
  evaporation_rate: 0.5
  elitism_factor: 5.0

  mmas:
    rho: 0.2

output:
  map_filename: "corlu_optimized_route.html"

osrm:
  host: "http://127.0.0.1:5000"