location:
  place_name: "Çorlu, Tekirdağ, Türkiye"

problem:
  strategy: "from_scenario"
  num_stops: 10
  scenario_filepath: "data/scenarios/corlu_varsayilan_10_durak.json"

aco:
  ant_count: 20

  iterations: 50

  alpha: 1.0

  beta: 5.0

  evaporation_rate: 0.5

output:
  map_filename: "corlu_optimized_route.html"